/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import com.sun.glass.events.KeyEvent;
import timetablems.DBConnect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Supun
 */
public class AddLecturer extends javax.swing.JFrame {

    /**
     * Creates new form AddLecturer
     */
    public AddLecturer() throws SQLException {
        initComponents();
        con = DBConnect.connect();
        
        fillBuilding();
        //date, time underline code
        String date = "<html><u> Date </u></html>";
        jLabel12.setText(date);
        String time = "<html><u> Time </u></html>";
        jLabel13.setText(time);
        // disabale Maximize button
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdep = new javax.swing.JComboBox<>();
        txtfac = new javax.swing.JComboBox<>();
        txtcen = new javax.swing.JComboBox<>();
        txtlev = new javax.swing.JComboBox<>();
        txtbui = new javax.swing.JComboBox<>();
        Clear = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Generate = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txteid = new javax.swing.JTextField();
        txtran = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttue = new javax.swing.JTextField();
        txtmon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtwen = new javax.swing.JTextField();
        txtthu = new javax.swing.JTextField();
        txtfri = new javax.swing.JTextField();
        txtsat = new javax.swing.JTextField();
        txtsun = new javax.swing.JTextField();
        errorname = new javax.swing.JLabel();
        erroreid = new javax.swing.JLabel();
        errormon = new javax.swing.JLabel();
        errortue = new javax.swing.JLabel();
        errorwen = new javax.swing.JLabel();
        errorthu = new javax.swing.JLabel();
        errorfri = new javax.swing.JLabel();
        errorsat = new javax.swing.JLabel();
        errorsun = new javax.swing.JLabel();
        errorrank = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Lecturers");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 28, -1, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Lecturer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 98, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Department");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 243, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Center");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Faculty");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 195, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Employee ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 145, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Building");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 341, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Level");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 394, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rank");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 443, 90, -1));

        txtdep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CSE", "CS", "SE", " " }));
        txtdep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdepKeyReleased(evt);
            }
        });
        jPanel1.add(txtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 237, 163, 29));

        txtfac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Business", "Humanities & Sciences" }));
        txtfac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfacKeyReleased(evt);
            }
        });
        jPanel1.add(txtfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 189, -1, 28));

        txtcen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "Metro", "Matara", "Kandy", "Kurunagala", "Jaffna" }));
        txtcen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcenKeyReleased(evt);
            }
        });
        jPanel1.add(txtcen, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 284, 163, 29));

        txtlev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        txtlev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlevKeyReleased(evt);
            }
        });
        jPanel1.add(txtlev, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 387, 163, 31));

        txtbui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuiKeyReleased(evt);
            }
        });
        jPanel1.add(txtbui, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 334, 163, 30));

        Clear.setBackground(new java.awt.Color(0, 102, 204));
        Clear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClearKeyReleased(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 480, 101, 34));

        Save.setBackground(new java.awt.Color(0, 102, 204));
        Save.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 480, 101, 34));

        Generate.setBackground(new java.awt.Color(0, 102, 204));
        Generate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Generate.setForeground(new java.awt.Color(255, 255, 255));
        Generate.setText("Generate");
        Generate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        Generate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GenerateKeyReleased(evt);
            }
        });
        jPanel1.add(Generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 480, -1, 34));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 94, 163, 28));

        txteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteidActionPerformed(evt);
            }
        });
        txteid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txteidKeyReleased(evt);
            }
        });
        jPanel1.add(txteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 140, 163, 31));

        txtran.setEditable(false);
        txtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtranActionPerformed(evt);
            }
        });
        txtran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtranKeyReleased(evt);
            }
        });
        jPanel1.add(txtran, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 439, 163, 29));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Active hours of Lecturers");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Days");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Monday");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tuesday");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Wendsday");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Thursday");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Friday");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Saturday");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Sunday");

        txttue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttueActionPerformed(evt);
            }
        });
        txttue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttueKeyReleased(evt);
            }
        });

        txtmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonActionPerformed(evt);
            }
        });
        txtmon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmonKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Time");

        txtwen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtwenKeyReleased(evt);
            }
        });

        txtthu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtthuKeyReleased(evt);
            }
        });

        txtfri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfriKeyReleased(evt);
            }
        });

        txtsat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsatKeyReleased(evt);
            }
        });

        txtsun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsunKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfri, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtthu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttue, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtsun, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txttue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtwen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtthu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfri, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        errorname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 188, 28));

        erroreid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        erroreid.setText("  ");
        jPanel1.add(erroreid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 188, 28));

        errormon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errormon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 201, 28));

        errortue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errortue, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 201, 28));

        errorwen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorwen, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 201, 28));

        errorthu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 201, 28));

        errorfri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorfri, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 201, 28));

        errorsat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorsat, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 201, 28));

        errorsun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorsun, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 201, 28));

        errorrank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errorrank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 439, 194, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Hint :- 08.00-17.30 or Not Available");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, 23));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void fillBuilding(){
        try{
            
            String sql = "select * from location group by building";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                
                String group = rs.getString("building");
                txtbui.addItem(group); 
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        // TODO add your handling code here:
        
        String EmpID =txteid.getText();
        String Level = txtlev.getSelectedItem().toString();
        
        String Rank = Level + "." + EmpID ;
        txtran.setText(Rank);
    }//GEN-LAST:event_GenerateActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
            txtname.setText("");
            txteid.setText("");
            txtfac.setSelectedIndex(0);
            txtdep.setSelectedIndex(0);
            txtcen.setSelectedIndex(0);
            txtbui.setSelectedIndex(0);
            txtlev.setSelectedIndex(0);
            txtran.setText("");
            txtmon.setText("");
            txttue.setText("");
            txtwen.setText("");
            txtthu.setText("");
            txtfri.setText("");
            txtsat.setText("");
            txtsun.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void txtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtranActionPerformed

    private void txtmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().trim().isEmpty()){
            errorname.setText("* Please Enter Lecturer Name.!");
        }
        else
            errorname.setText("");
            
        
        if(txteid.getText().trim().isEmpty()){
            erroreid.setText("* Please Enter Employee ID.!");
        }
        else
            erroreid.setText("");
        
        if(txtmon.getText().trim().isEmpty()){
            errormon.setText("* Please Enter Active Hours.!");
        }
        else
            errormon.setText("");
        
        if(txttue.getText().trim().isEmpty()){
            errortue.setText("* Please Enter Active Hours.!");
        }
        else
            errortue.setText("");
        
        if(txtwen.getText().trim().isEmpty()){
            errorwen.setText("* Please Enter Active Hours.!");
        }
        else
            errorwen.setText("");
        
        if(txtthu.getText().trim().isEmpty()){
            errorthu.setText("* Please Enter Active Hours.!");
        }
        else
            errorthu.setText("");
        
        if(txtfri.getText().trim().isEmpty()){
            errorfri.setText("* Please Enter Active Hours.!");
        }
        else
            errorfri.setText("");
        
        if(txtsat.getText().trim().isEmpty()){
            errorsat.setText("* Please Enter Active Hours.!");
        }
        else
            errorsat.setText("");
        
        if(txtsun.getText().trim().isEmpty()){
            errorsun.setText("* Please Enter Active Hours.!");
        }
        else
            errorsun.setText("");
     //don't save data until click ganerate button     
        if(txtran.getText().length()<=0 ) {
        
             JOptionPane.showMessageDialog(null, "Please click Genarate button");    
        }
        else{  
        
        try {
        
            String LecName = txtname.getText();
            String EmpID = txteid.getText();
            String Faculty = txtfac.getSelectedItem().toString();
            String Department = txtdep.getSelectedItem().toString();
            String Center = txtcen.getSelectedItem().toString();
            String Building = txtbui.getSelectedItem().toString();            
            String Level = txtlev.getSelectedItem().toString();
            String Rank = txtran.getText();        
            String Monday = txtmon.getText();
            String Tuesday = txttue.getText();
            String Wednesday = txtwen.getText();
            String Thursday = txtthu.getText();
            String Friday = txtfri.getText();
            String Saturday = txtsat.getText();
            String Sunday = txtsun.getText();

            
                pst = con.prepareStatement("insert into lecturer(name,eid,faculty,department,center,building,level,rank,monday,tuesday,wednesday,thursday,friday,saturday,sunday) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1,LecName);
                pst.setString(2,EmpID);
                pst.setString(3,Faculty);
                pst.setString(4,Department);
                pst.setString(5,Center);
                pst.setString(6,Building);
                pst.setString(7,Level);
                pst.setString(8,Rank);
                pst.setString(9,Monday);
                pst.setString(10,Tuesday);
                pst.setString(11,Wednesday);
                pst.setString(12,Thursday);
                pst.setString(13,Friday);
                pst.setString(14,Saturday);
                pst.setString(15,Sunday);
                
                pst.executeUpdate();
                
            JOptionPane.showMessageDialog(this, "New Lecturer Added Successfully");
           // this.setVisible(false);
            
            txtname.setText("");
            txteid.setText("");
            txtfac.setSelectedIndex(0);
            txtdep.setSelectedIndex(0);
            txtcen.setSelectedIndex(0);
            txtbui.setSelectedIndex(0);
            txtlev.setSelectedIndex(0);
            txtran.setText("");
            txtmon.setText("");
            txttue.setText("");
            txtwen.setText("");
            txtthu.setText("");
            txtfri.setText("");
            txtsat.setText("");
            txtsun.setText("");
            
            } catch (SQLException ex) {
                Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_SaveActionPerformed
    }
    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[Mr|Ms|Dr|Prof]{2,4}[.][ ][a-zA-Z]{2,30}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtname.getText());
        if(!match.matches()){
            errorname.setText("* Leacturer Name is invalid !!");
            //Save.setEnabled(false);
        }
        else{
            errorname.setText(null);
            //Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txteid.requestFocus();
            }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtranKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtranKeyReleased

    private void txteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteidActionPerformed

    private void txteidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txteidKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txteid.getText());

        if(!match.matches()){
            erroreid.setText("* EID number is incorrect !!");
            //Save.setEnabled(false);
        }
        else{
            erroreid.setText(null);
            //Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtfac.requestFocus();
            }
    }//GEN-LAST:event_txteidKeyReleased

    private void txtmonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtmon.getText());

        if(!match.matches()){
            errormon.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errormon.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txttue.requestFocus();
            }
    }//GEN-LAST:event_txtmonKeyReleased

    private void txttueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttueKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txttue.getText());

        if(!match.matches()){
            errortue.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errortue.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtwen.requestFocus();
            }
    }//GEN-LAST:event_txttueKeyReleased

    private void txtwenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtwenKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtwen.getText());

        if(!match.matches()){
            errorwen.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errorwen .setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtthu.requestFocus();
            }
    }//GEN-LAST:event_txtwenKeyReleased

    private void txtthuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtthuKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtthu.getText());

        if(!match.matches()){
            errorthu.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errorthu.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtfri.requestFocus();
            }
    }//GEN-LAST:event_txtthuKeyReleased

    private void txtfriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfriKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtfri.getText());

        if(!match.matches()){
            errorfri.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errorfri.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtsat.requestFocus();
            }
    }//GEN-LAST:event_txtfriKeyReleased

    private void txtsatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsatKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtsat.getText());

        if(!match.matches()){
            errorsat.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errorsat.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtsun.requestFocus();
            }
    }//GEN-LAST:event_txtsatKeyReleased

    private void txtsunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsunKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{2}[.][0-9]{2}[-][0-9]{2}[.][0-9]{2}|[a-zA-Z]{1,10}[ ][a-zA-Z]{1,15}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtsun.getText());

        if(!match.matches()){
            errorsun.setText("* Please follow the hint..!!");
            Save.setEnabled(false);
        }
        else{
            errorsun.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Clear.requestFocus();
            }
    }//GEN-LAST:event_txtsunKeyReleased

    private void txttueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttueActionPerformed

    private void txtfacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfacKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtdep.requestFocus();
            }
    }//GEN-LAST:event_txtfacKeyReleased

    private void txtdepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtcen.requestFocus();
            }
    }//GEN-LAST:event_txtdepKeyReleased

    private void txtcenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcenKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtbui.requestFocus();
            }
    }//GEN-LAST:event_txtcenKeyReleased

    private void txtbuiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuiKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtlev.requestFocus();
            }
    }//GEN-LAST:event_txtbuiKeyReleased

    private void txtlevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlevKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Generate.requestFocus();
            }
    }//GEN-LAST:event_txtlevKeyReleased

    private void GenerateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenerateKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtmon.requestFocus();
            }
    }//GEN-LAST:event_GenerateKeyReleased

    private void ClearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClearKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Save.requestFocus();
            }
    }//GEN-LAST:event_ClearKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddLecturer().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Generate;
    private javax.swing.JButton Save;
    private javax.swing.JLabel erroreid;
    private javax.swing.JLabel errorfri;
    private javax.swing.JLabel errormon;
    private javax.swing.JLabel errorname;
    private javax.swing.JLabel errorrank;
    private javax.swing.JLabel errorsat;
    private javax.swing.JLabel errorsun;
    private javax.swing.JLabel errorthu;
    private javax.swing.JLabel errortue;
    private javax.swing.JLabel errorwen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> txtbui;
    private javax.swing.JComboBox<String> txtcen;
    private javax.swing.JComboBox<String> txtdep;
    private javax.swing.JTextField txteid;
    private javax.swing.JComboBox<String> txtfac;
    private javax.swing.JTextField txtfri;
    private javax.swing.JComboBox<String> txtlev;
    private javax.swing.JTextField txtmon;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtran;
    private javax.swing.JTextField txtsat;
    private javax.swing.JTextField txtsun;
    private javax.swing.JTextField txtthu;
    private javax.swing.JTextField txttue;
    private javax.swing.JTextField txtwen;
    // End of variables declaration//GEN-END:variables
}
