/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class AddNotAvailableTimes extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public AddNotAvailableTimes() {
        initComponents();
        
        //Database Connection
        con = DBConnection.ConnectionDB();
        
       setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        lCombo();
        groupCombo();
        subGroupCombo();
        locCombo();
        sCombo();
        
        
    }
    
    //Close current JFrame when close button pressed
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    //Getting the name of the lecturer
    private void lCombo(){
        
        try{
        
            String sql = "SELECT * FROM lecturer";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
            
                String name=rs.getString("name");
                lectCombo.addItem(name);
            
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    //Getting group IDs    
    private void groupCombo(){
        
        try{
        
            String sql = "SELECT * FROM student";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
            
                String name=rs.getString("groupid");
                groupCombo.addItem(name);
            
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    //Getting sub group IDs    
    private void subGroupCombo(){
        
        try{
        
            String sql = "SELECT * FROM student";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
            
                String name=rs.getString("subgroupid");
                subGroupCombo.addItem(name);
            
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    //Getting room   
    private void locCombo(){
        
        try{
        
            String sql = "SELECT * FROM location";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
            
                String name=rs.getString("room");
                locCombo.addItem(name);
            
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    //Getting session   
    private void sCombo(){
        
        try{
        
            String sql = "SELECT * FROM Session";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
            
                String name=rs.getString("alldetails");
                sCombo.addItem(name);
            
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    
    
    //Reset values
    private void resetFields(){
    
        lectCombo.setSelectedIndex(0);
        groupCombo.setSelectedIndex(0);
        subGroupCombo.setSelectedIndex(0);
        sCombo.setSelectedIndex(0);
        dayCombo.setSelectedIndex(0);
        locCombo.setSelectedIndex(0);
        startCombo.setSelectedIndex(0);
        endCombo.setSelectedIndex(0);
        
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        groupCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        locCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        subGroupCombo = new javax.swing.JComboBox<>();
        lectCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dayCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sCombo = new javax.swing.JComboBox<>();
        btnClose = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        startCombo = new javax.swing.JComboBox<>();
        endCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Not Available Times");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 44, 267, 61));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Select Session");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Select Group");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 20));

        groupCombo.setBackground(new java.awt.Color(240, 240, 240));
        groupCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        groupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));
        groupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupComboActionPerformed(evt);
            }
        });
        jPanel1.add(groupCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Select Sub Group");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 20));

        locCombo.setBackground(new java.awt.Color(240, 240, 240));
        locCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));
        locCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locComboActionPerformed(evt);
            }
        });
        jPanel1.add(locCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 170, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Select Room");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 20));

        subGroupCombo.setBackground(new java.awt.Color(240, 240, 240));
        subGroupCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));
        subGroupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subGroupComboActionPerformed(evt);
            }
        });
        jPanel1.add(subGroupCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, -1));

        lectCombo.setBackground(new java.awt.Color(240, 240, 240));
        lectCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lectCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));
        lectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectComboActionPerformed(evt);
            }
        });
        jPanel1.add(lectCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Select Day");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 20));

        dayCombo.setBackground(new java.awt.Color(240, 240, 240));
        dayCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        dayCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayComboActionPerformed(evt);
            }
        });
        jPanel1.add(dayCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 170, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Start Time");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 93, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("End Time");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 93, 20));

        btnReset.setBackground(new java.awt.Color(0, 102, 204));
        btnReset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset All");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 464, 93, 34));

        btnSubmit.setBackground(new java.awt.Color(0, 102, 204));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Save");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 464, 93, 34));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Select Lecturer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 117, 20));

        sCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));
        jPanel1.add(sCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 290, -1));

        btnClose.setBackground(new java.awt.Color(0, 102, 204));
        btnClose.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 464, 93, 34));

        btnView.setBackground(new java.awt.Color(0, 102, 204));
        btnView.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 464, 93, 34));

        startCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30" }));
        jPanel1.add(startCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        endCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30" }));
        jPanel1.add(endCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupComboActionPerformed

    private void locComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locComboActionPerformed

    private void subGroupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subGroupComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subGroupComboActionPerformed

    private void lectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectComboActionPerformed

    private void dayComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayComboActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        String lecName= lectCombo.getSelectedItem().toString();
        String stgroup= groupCombo.getSelectedItem().toString();
	String subGroup= subGroupCombo.getSelectedItem().toString();
	String sessionSign= sCombo.getSelectedItem().toString();
	System.out.println(sessionSign);
	String day= dayCombo.getSelectedItem().toString();
	String room= locCombo.getSelectedItem().toString();
        String startTime= startCombo.getSelectedItem().toString();
        String endTime= endCombo.getSelectedItem().toString();
        
        if(dayCombo.getSelectedItem().equals("SELECT")) {
		day="--";
            }else if(dayCombo.getSelectedItem().equals("MONDAY")) {
		day="Monday";
            }else if(dayCombo.getSelectedItem().equals("TUESDAY")) {
		day="Tuesday";
            }else if(dayCombo.getSelectedItem().equals("WEDNESDAY")) {
		day="Wednesday";
            }else if(dayCombo.getSelectedItem().equals("THURSDAY")) {
		day="Thursday";
            }else if(dayCombo.getSelectedItem().equals("FRIDAY")) {
		day="Friday";
            }else if(dayCombo.getSelectedItem().equals("SATURDAY")) {
                day="Saturday";
            }else if(dayCombo.getSelectedItem().equals("SUNDAY")) {
		day="Sunday";
            }
					
            if(lectCombo.getSelectedItem().equals("SELECT")) {
		JOptionPane.showMessageDialog(null, "Please Select Lecturer!!!");
            }			
                else if(groupCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Group!!!");
		}
		else if(subGroupCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Sub Group!!!");
		}
		else if(sCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Session Signatue!!!");
		}
                else if(dayCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Day!!!");
		}
                else if(locCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Room!!!");
		}
                else if(locCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Room!!!");
		}
                else if(startCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Starting time!!!");
		}
                else if(endCombo.getSelectedItem().equals("SELECT")) {
                    JOptionPane.showMessageDialog(null, "Please Select Ending time!!!");
		}
            
            else {
		try {

//		    String sql = "INSERT INTO not_available values(null, || lecName ||,|| stgroup ||,|| subGroup ||,|| sessionSign ||,|| day ||,|| room ||,|| startTime ||,|| endTime ||)";
//
//		    String sql1="INSERT INTO timeTable (t_id,startTime,||day||,LecName,endTime,stgroup,room)values (null,||startTime|| ,||sessionSign||,||lecName||,||endTime||,||subGroup||,||room||)";
//                    pst.executeUpdate(sql1);

                    pst = con.prepareStatement("INSERT INTO not_available values(null, '" + lecName + "','" + stgroup + "','" + subGroup + "','" + sessionSign + "','" + day + "','"+ room +"','" + startTime + "','"+ endTime +"')");
		    pst.executeUpdate();
                    
                    pst = con.prepareStatement("INSERT INTO timeTable (t_id,startTime,'"+day+"',lecName,endTime,stgroup,subGroup,room)values (null,'"+startTime+"' ,'"+sessionSign+"','"+lecName+"','"+endTime+"','"+stgroup+"','"+subGroup+"','"+room+"')");
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null,"Records Inserted Successfully!");
                    
//		    int x = pst.executeUpdate();
//		    if (x == 0) {
//		        JOptionPane.showMessageDialog(null, "This is alredy exist");
//		    } else {
//		        JOptionPane.showMessageDialog(null, "Successfully Inserted!");
//		    }
                    

		    //con.close();
		} catch (Exception exception) {
		    JOptionPane.showMessageDialog(null,"Something Went Wrong!","Insertion Failed!",JOptionPane.WARNING_MESSAGE);

		                	
		}
            }
            
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        ManageNotAvailableTimes in = new ManageNotAvailableTimes();
        in.setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNotAvailableTimes().setVisible(true);
            }
        });
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JComboBox<String> endCombo;
    private javax.swing.JComboBox<String> groupCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lectCombo;
    private javax.swing.JComboBox<String> locCombo;
    private javax.swing.JComboBox<String> sCombo;
    private javax.swing.JComboBox<String> startCombo;
    private javax.swing.JComboBox<String> subGroupCombo;
    // End of variables declaration//GEN-END:variables
}
