/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import com.sun.glass.events.KeyEvent;
import timetablems.DBConnect;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Supun
 */
public class AddSession extends javax.swing.JFrame {
    /**
     * Creates new form AddSession
     */
    public AddSession() throws SQLException {
        initComponents();
        con = DBConnect.connect();
        fillLecturer();
        fillSubject();
        fillGroup();
        fillTag();
        
        // disabale Maximize button
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        //jfram not close
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    ResultSet rs;
    
    private void fillLecturer(){
        try{
            
            String sql = "select * from lecturer ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String name = rs.getString("name");
                txtname1.addItem(name);
                txtname2.addItem(name);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void fillSubject(){
        try{
            
            String sql = "select * from subject";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                
                String code = rs.getString("s_code");
                txtscode.addItem(code);
                String name = rs.getString("name");
                txtsname.addItem(name);
            
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void fillGroup(){
        try{
            
            String sql = "select * from student";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                
                String group = rs.getString("subgroupid");
                txtgid.addItem(group); 
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
private void fillTag(){
        try{
            
            String sql = "select * from tag group by relatedtag";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                
                String Tag = rs.getString("relatedtag");
                txttag.addItem(Tag); 
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnos = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        errornos = new javax.swing.JLabel();
        errordur = new javax.swing.JLabel();
        txtname2 = new javax.swing.JComboBox<>();
        txtscode = new javax.swing.JComboBox<>();
        txtsname = new javax.swing.JComboBox<>();
        txtgid = new javax.swing.JComboBox<>();
        txttag = new javax.swing.JComboBox<>();
        txtdur = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Sessions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 49, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Select Lecturer(s) 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 112, 130, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Select Lecturer(s) 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 184, 130, 28));

        txtname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname1.setBorder(null);
        txtname1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname1ActionPerformed(evt);
            }
        });
        txtname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtname1KeyReleased(evt);
            }
        });
        jPanel1.add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 110, 206, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Subject Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 254, 130, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 323, 130, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sub Group ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 112, 96, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Select Tag");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 184, 96, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("No. of Students");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 252, -1, 28));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Durations");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 321, 96, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Hrs");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 321, 22, 28));

        txtnos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnos.setBorder(null);
        txtnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnosKeyReleased(evt);
            }
        });
        jPanel1.add(txtnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 252, 200, 32));

        Clear.setBackground(new java.awt.Color(0, 102, 204));
        Clear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClearKeyReleased(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 115, 39));

        Save.setBackground(new java.awt.Color(0, 102, 204));
        Save.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        Save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SaveKeyPressed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 111, 39));

        errornos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errornos, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 255, 200, 29));

        errordur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(errordur, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 324, 197, 29));

        txtname2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Not Selected]" }));
        txtname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtname2KeyReleased(evt);
            }
        });
        jPanel1.add(txtname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 182, 206, 32));

        txtscode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtscode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtscodeKeyReleased(evt);
            }
        });
        jPanel1.add(txtscode, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 252, 206, 32));

        txtsname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 321, 206, 32));

        txtgid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtgid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgidKeyReleased(evt);
            }
        });
        jPanel1.add(txtgid, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 110, 200, 32));

        txttag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttagKeyReleased(evt);
            }
        });
        jPanel1.add(txttag, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 182, 200, 32));

        txtdur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdur.setBorder(null);
        txtdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurActionPerformed(evt);
            }
        });
        txtdur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdurKeyReleased(evt);
            }
        });
        jPanel1.add(txtdur, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 321, 200, 32));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
         if(txtnos.getText().trim().isEmpty()){
            errornos.setText("* Please Enter No. of Students.!");
        }
        else
            errornos.setText("");
        
        if(txtdur.getText().trim().isEmpty()){
            errordur.setText("* Please Enter Duration Hours.!");
        }
        else
            errordur.setText(""); 
          
        if(txtnos.getText().trim().isEmpty() || txtdur.getText().trim().isEmpty()){
            Component frame = null;
            
            JOptionPane.showMessageDialog(frame, " Please fill in a valid value ");
        }
        else{  
        
        try {
        
            String Lecture1 = txtname1.getSelectedItem().toString();
            String Lecture2 = txtname2.getSelectedItem().toString();
            String S_code = txtscode.getSelectedItem().toString();
            String S_name = txtsname.getSelectedItem().toString();
            String Group = txtgid.getSelectedItem().toString();            
            String Tag = txttag.getSelectedItem().toString();
            String NOStudent = txtnos.getText();        
            String Duration = txtdur.getText();
            String Details = Lecture1+", "+Lecture2+", "+S_code+", "+S_name+", "+Group+", "+Tag+", "+NOStudent+", "+Duration;            
            String Details1 = Lecture1+", "+Lecture2+", "+S_code+", "+S_name+", "+Group+", "+Tag;
                    
                pst = con.prepareStatement("insert into session (name1,name2,s_code,s_name,gid,tag,nuofstu,duration,alldetails,rajitha) values(?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1,Lecture1);
                pst.setString(2,Lecture2);
                pst.setString(3,S_code);
                pst.setString(4,S_name);
                pst.setString(5,Group);
                pst.setString(6,Tag);
                pst.setString(7,NOStudent);
                pst.setString(8,Duration);
                pst.setString(9,Details);
                pst.setString(10,Details1);
                
                pst.executeUpdate();
                
            JOptionPane.showMessageDialog(this, "New Session Added Successfully");
           // this.setVisible(false);
            
            txtname1.setSelectedIndex(0);
            txtname2.setSelectedIndex(0);
            txtscode.setSelectedIndex(0);
            txtsname.setSelectedIndex(0);
            txtgid.setSelectedIndex(0);
            txttag.setSelectedIndex(0);
            txtnos.setText("");
            txtdur.setText("");
            
            } catch (SQLException ex) {
                Logger.getLogger(AddLecturer.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }  
    }//GEN-LAST:event_SaveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
           
            txtname1.setSelectedIndex(0);
            txtname2.setSelectedIndex(0);
            txtscode.setSelectedIndex(0);
            txtsname.setSelectedIndex(0);
            txtgid.setSelectedIndex(0);
            txttag.setSelectedIndex(0);
            txtnos.setText("");
            txtdur.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void SaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SaveKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Save.requestFocus();
            }
    }//GEN-LAST:event_SaveKeyPressed

    private void txtnosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnosKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{1,4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtnos.getText());

        if(!match.matches()){
            errornos.setText("* Number is incorrect !!");
            Save.setEnabled(false);
        }
        else{
            errornos.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtdur.requestFocus();
            }
    }//GEN-LAST:event_txtnosKeyReleased

    private void txtdurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdurKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[0-9]{1}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtdur.getText());

        if(!match.matches()){
            errordur.setText("* Number is incorrect !!");
            Save.setEnabled(false);
        }
        else{
            errordur.setText(null);
            Save.setEnabled(true);
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Clear.requestFocus();
            }
    }//GEN-LAST:event_txtdurKeyReleased

    private void txtname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtname1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtname2.requestFocus();
        }
    }//GEN-LAST:event_txtname1KeyReleased

    private void txtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1ActionPerformed

    private void txtname2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtname2KeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             txtscode.requestFocus();
         }
    }//GEN-LAST:event_txtname2KeyReleased

    private void txtscodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtscodeKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             txtsname.requestFocus();
         }
    }//GEN-LAST:event_txtscodeKeyReleased

    private void txtsnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsnameKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             txtgid.requestFocus();
         }
    }//GEN-LAST:event_txtsnameKeyReleased

    private void txtgidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgidKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             txttag.requestFocus();
         }
    }//GEN-LAST:event_txtgidKeyReleased

    private void txttagKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttagKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             txtnos.requestFocus();
         }
    }//GEN-LAST:event_txttagKeyReleased

    private void ClearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClearKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             Save.requestFocus();
         }
    }//GEN-LAST:event_ClearKeyReleased

    private void txtdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddSession().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddSession.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }); 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Save;
    private javax.swing.JLabel errordur;
    private javax.swing.JLabel errornos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdur;
    private javax.swing.JComboBox<String> txtgid;
    private javax.swing.JComboBox<String> txtname1;
    private javax.swing.JComboBox<String> txtname2;
    private javax.swing.JTextField txtnos;
    private javax.swing.JComboBox<String> txtscode;
    private javax.swing.JComboBox<String> txtsname;
    private javax.swing.JComboBox<String> txttag;
    // End of variables declaration//GEN-END:variables
}
