/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manujaya
 */
public class AddSessionLocation extends javax.swing.JFrame {

    Connection conn = null;
        PreparedStatement pst =null;
        ResultSet rs=null;
        DefaultTableModel model = new DefaultTableModel();
        
    public AddSessionLocation() {
        initComponents();
        conn = AddSessionLocation.ConnectDb();
        
        Object col[] = {""};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        
        updateTable();
        Fillcombo();
        load();
        
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void clearsub(){
    
        sroom.setText("");   
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        list = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Lecturer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tags = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Subcd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        grp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stcount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Sub = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sroom = new javax.swing.JTextField();
        remove = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Session Room");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Session :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, -1, -1));

        list.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                listPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });
        jPanel1.add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 354, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Lecturer :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));

        Lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecturerMouseClicked(evt);
            }
        });
        Lecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerActionPerformed(evt);
            }
        });
        jPanel1.add(Lecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 122, 145, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Subject :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 126, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tag :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        tags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsActionPerformed(evt);
            }
        });
        jPanel1.add(tags, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 162, 145, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject Code :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 166, -1, -1));

        Subcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubcdActionPerformed(evt);
            }
        });
        jPanel1.add(Subcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 162, 167, 29));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Group :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, -1, -1));

        grp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpActionPerformed(evt);
            }
        });
        jPanel1.add(grp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 202, 145, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Student Count :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 206, -1, -1));

        stcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stcountActionPerformed(evt);
            }
        });
        jPanel1.add(stcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 202, 167, 29));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select from below list..."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 298, 143, 153));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Selected Session");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 263, -1, -1));

        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        jPanel1.add(Sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 122, 167, 29));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Selected Room");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 469, -1, -1));

        sroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sroomActionPerformed(evt);
            }
        });
        jPanel1.add(sroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 497, 138, 33));

        remove.setBackground(new java.awt.Color(0, 102, 204));
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 492, 90, 38));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 298, 325, 153));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Available Rooms");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 263, -1, -1));

        add.setBackground(new java.awt.Color(0, 102, 204));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 492, 91, 38));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Connection ConnectDb(){
        try
        {
        Class.forName("org.sqlite.JDBC");
        Connection conn = DriverManager.getConnection("jdbc:sqlite:ttms.db");
        return conn;
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
    
    
    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listActionPerformed

    private void LecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LecturerActionPerformed

    private void tagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagsActionPerformed

    private void SubcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubcdActionPerformed

    private void grpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grpActionPerformed

    private void stcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stcountActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
     
        String tblroom = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        
        
        sroom.setText(tblroom);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubActionPerformed

    private void sroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sroomActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow()==-1){
            if(jTable2.getRowCount()==0){
            
            JOptionPane.showMessageDialog(null, "No data to delete",
                    "Student Result System",JOptionPane.OK_OPTION);
           
            }else{
                    JOptionPane.showMessageDialog(null, "Select a Row to delete",
                    "Student Result System",JOptionPane.OK_OPTION);
            }
        }else{
             model.removeRow(jTable2.getSelectedRow());
            }
    }//GEN-LAST:event_removeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        
       
        
    }//GEN-LAST:event_listMouseClicked

    private void listPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_listPopupMenuWillBecomeInvisible
         String item = (String)list.getSelectedItem();
        String sql = "select * from Session where alldetails = ?";
        
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            rs = pst.executeQuery();
            
            if(rs.next()){
            
                Lecturer.setText(rs.getString("name1"));
                Sub.setText(rs.getString("s_name"));
                tags.setText(rs.getString("tag"));
                Subcd.setText(rs.getString("s_code"));
                grp.setText(rs.getString("gid"));
                stcount.setText(rs.getString("nuofstu"));
            
                Lecturer.setEditable(false);
                Sub.setEditable(false);
                tags.setEditable(false);
                Subcd.setEditable(false);
                grp.setEditable(false);
                stcount.setEditable(false);
                
            }
            
        
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_listPopupMenuWillBecomeInvisible

    private void LecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecturerMouseClicked
       
    }//GEN-LAST:event_LecturerMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String sql="INSERT INTO session_location(Session,Room,RoomSign)VALUES(?,?,?)";
        
      try
      {
          pst = conn.prepareStatement(sql);
         
          String value=list.getSelectedItem().toString();
           
          pst.setString(1,value);
          pst.setString(2, sroom.getText());
          pst.setString(3, value + "-" + sroom.getText());
          
          
          
          pst.execute();
            JOptionPane.showMessageDialog(null, "Room Assigned to Session");
            
            rs.close();
            pst.close();
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null, e);
      }
      
      load();
    }//GEN-LAST:event_addActionPerformed

     public void load(){
    
        int a;
        try{
            pst = conn.prepareStatement("select Session,Room from session_location");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
            model = (DefaultTableModel)jTable2.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
            
                Vector v2 = new Vector();
                for(int i = 1; i<=a; i++){
                
                 v2.add(rs.getString("Session"));
                 v2.add(rs.getString("Room"));
                
                
                }
                   model.addRow(v2);
            }
        }
        
        catch(Exception e){}
    
    }
    
    public void updateTable(){
    
        String sql="Select room from location";
        
        try
        {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[1];
            
            while(rs.next()){
                columnData [0] = rs.getString("room");
                                
                model.addRow(columnData);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
   private void Fillcombo(){
   try{
    String sql ="select alldetails from Session";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    
    while(rs.next()){
      String alldetails =rs.getString("alldetails");
      list.addItem(alldetails);
    
    }
   
   }catch(Exception e){
   
    JOptionPane.showMessageDialog(null, e);
   }
   
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSessionLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSessionLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSessionLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSessionLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSessionLocation().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lecturer;
    private javax.swing.JTextField Sub;
    private javax.swing.JTextField Subcd;
    private javax.swing.JButton add;
    private javax.swing.JTextField grp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> list;
    private javax.swing.JButton remove;
    private javax.swing.JTextField sroom;
    private javax.swing.JTextField stcount;
    private javax.swing.JTextField tags;
    // End of variables declaration//GEN-END:variables
}
