/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 94763
 */
public class session_manage extends javax.swing.JFrame {

    // Connection conn = null;
    //   PreparedStatement pst  = null;
    ResultSet rs = null;
    // DefaultTableModel model = new DefaultTableModel();

    public session_manage() {
        initComponents();
        conn = AddTags.ConnectDb();
        load();
        Fillcom();
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    Connection conn;
    PreparedStatement pst;
    DefaultTableModel df, df1, df2;

    public static Connection ConnectDb() {

        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:ttms.db");
            return conn;
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            return null;
        }

    }

    public void load() {
        String sql = "select* from Session";
        int a;
        try {

            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel) jTable3.getModel();
            df1 = (DefaultTableModel) jTable2.getModel();
            df2 = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            df1.setRowCount(0);
            df2.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= a; i++) {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("name1"));
                    v2.add(rs.getString("name2"));
                    v2.add(rs.getString("s_code"));
                    v2.add(rs.getString("s_name"));
                    v2.add(rs.getString("gid"));
                    v2.add(rs.getString("tag"));
                    v2.add(rs.getString("nuofstu"));
                    v2.add(rs.getString("duration"));
                    v2.add(rs.getString("alldetails"));

                }

               df.addRow(v2);
               df1.addRow(v2);
               df2.addRow(v2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(session_manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFrame1 = new javax.swing.JFrame();
        menuBar5 = new java.awt.MenuBar();
        menu9 = new java.awt.Menu();
        menu10 = new java.awt.Menu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        Sserach = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Sserach1 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Ssearch3 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        popupMenu1.setLabel("popupMenu1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu9.setLabel("File");
        menuBar5.add(menu9);

        menu10.setLabel("Edit");
        menuBar5.add(menu10);

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(28, 28, 28)
                .addComponent(jButton9)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane2KeyPressed(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 89, 51));

        jButton5.setBackground(new java.awt.Color(0, 51, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 95, 51));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name1", "Name2", "Stu-Code", "Stu-Name", "gID", "Tag", "Num of Stu", "Duration", "All Detaills"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 202));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 230, -1));

        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 280, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sessions");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 117, 20));

        jButton12.setBackground(new java.awt.Color(0, 51, 255));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 93, 39));

        Sserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SserachActionPerformed(evt);
            }
        });
        jPanel3.add(Sserach, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 215, 29));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 400));

        jTabbedPane2.addTab("Consecutive", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Session 1", "Session  2", "Stu-code", "Stu-name", "GID", "Tag", "Num Of Stu", "duration", "allDetails"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 231));

        jButton6.setBackground(new java.awt.Color(0, 51, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ADD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 100, 48));

        jButton7.setBackground(new java.awt.Color(0, 51, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 101, 48));

        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, -1));

        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 240, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sessions");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 111, -1));

        Sserach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sserach1ActionPerformed(evt);
            }
        });
        jPanel2.add(Sserach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 215, 29));

        jButton13.setBackground(new java.awt.Color(0, 51, 255));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 93, 39));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 400));

        jTabbedPane2.addTab("Parallel", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name1", "Name2", "Stu-Code", "Stu-Name", "GID", "Tag", "No of Stu", "Duration", "All Details"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 219));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 104, 46));

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, 46));

        jPanel4.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 240, -1));

        jPanel4.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 270, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sessions");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        Ssearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ssearch3ActionPerformed(evt);
            }
        });
        jPanel4.add(Ssearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 220, 30));

        jButton14.setBackground(new java.awt.Color(0, 51, 255));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Search ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 105, 38));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 400));

        jTabbedPane2.addTab("Non Overlapping ", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(0, 51, 255));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("ADD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 258, 72));

        jButton11.setBackground(new java.awt.Color(0, 51, 255));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("View");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 258, 72));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 400));

        jTabbedPane2.addTab("Not Available Times", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 670));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private  void Fillcom() {
        
        
    
         try
                 {
             
       
             pst = conn.prepareStatement("select * from Session");
              ResultSet rs = pst.executeQuery();
              
              
              while(rs.next()){
               String name = rs.getString("rajitha");
               jComboBox1.addItem(name);
                jComboBox2.addItem(name);
                    jComboBox3.addItem(name);
                     jComboBox4.addItem(name);
                     jComboBox5.addItem(name);
                     jComboBox6.addItem(name);
                     
              }
            
             
       }
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(null, "lost");
        }
    }  
    
    
 
    
    
    
    private void jTabbedPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
        
                
        String session1 =   jComboBox3.getSelectedItem().toString();
         String session2 =   jComboBox4.getSelectedItem().toString();
         
         String[] array1 =  session1.split("/");
          String[] array2 =  session2.split("/");
          
         String s1_lecname1 = array1[0];  
         String s1_lecname2 = array1[1]; 
         String s1_subcode = array1[2]; 
         String s1_sname = array1[3]; 
         String s1_groupid = array1[4]; 
         String s1_tag = array1[5]; 
         
           
         String s2_lecname1 = array2[0];  
         String s2_lecname2 = array2[1]; 
         String s2_subcode = array2[2]; 
         String s2_sname = array2[3]; 
         String s2_groupid = array2[4]; 
         String s2_tag = array2[5]; 
         
         
         String sql = "INSERT INTO parsessions (s1_lecname1,s1_lecname2,s1_subcode,s1_subname,s1_groupid,s1_tag,s2_lecname1,s2_lecname2,s2_subcode,s2_subname,s2_groupid,s2_tag)VALUES('"+s1_lecname1+"','"+s1_lecname2+"','"+s1_subcode+"','"+s1_sname+"','"+s1_groupid +"','"+s1_tag+"','"+s2_lecname1+"','"+s2_lecname2+"','"+s2_subcode+"','"+s2_sname+"','"+s2_groupid+"','"+s2_tag+"')";
         try
                 {
             
                     
                      pst = conn.prepareStatement(sql);
               
                        pst.execute();
                       JOptionPane.showMessageDialog(null, "Parallel session  added");
             
                   }
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(null, "Error whille adding session ");
        }
    
         
        

                                           
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          
               
        String session1 =   jComboBox1.getSelectedItem().toString();
         String session2 =   jComboBox2.getSelectedItem().toString();
         
         String[] array1 =  session1.split("/");
          String[] array2 =  session2.split("/");
          
         String s1_lecname1 = array1[0];  
         String s1_lecname2 = array1[1]; 
         String s1_subcode = array1[2]; 
         String s1_sname = array1[3]; 
         String s1_groupid = array1[4]; 
         String s1_tag = array1[5]; 
         
           
         String s2_lecname1 = array2[0];  
         String s2_lecname2 = array2[1]; 
         String s2_subcode = array2[2]; 
         String s2_sname = array2[3]; 
         String s2_groupid = array2[4]; 
         String s2_tag = array2[5]; 
         
         
         String sql = "INSERT INTO consessions (s1_lecname1,s1_lecname2,s1_subcode,s1_sname,s1_groupid,s1_tag,s2_lecname1,s2_lecname2,s2_subcode,s2_sname,s2_groupid,s2_tag)VALUES('"+s1_lecname1+"','"+s1_lecname2+"','"+s1_subcode+"','"+s1_sname+"','"+s1_groupid +"','"+s1_tag+"','"+s2_lecname1+"','"+s2_lecname2+"','"+s2_subcode+"','"+s2_sname+"','"+s2_groupid+"','"+s2_tag+"')";
         try
                 {
             
                     
                      pst = conn.prepareStatement(sql);
               
              pst.execute();
             JOptionPane.showMessageDialog(null, "Consecutive session  added");
             
       }
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(null, "loset");
        }
    
         
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ManageNotAvailableTimes as = new ManageNotAvailableTimes();
        as.setVisible(true);

       


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        Consecutie jf1 = new Consecutie();
        jf1.show();

        dispose();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        Parallel jf1 = new Parallel();
        jf1.show();

        dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        NonOverlapping jf1 = new NonOverlapping();
        jf1.show();

        dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

          
                
        String session1 =   jComboBox5.getSelectedItem().toString();
         String session2 =   jComboBox6.getSelectedItem().toString();
         
         String[] array1 =  session1.split("/");
          String[] array2 =  session2.split("/");
          
         String s1_lecname1 = array1[0];  
         String s1_lecname2 = array1[1]; 
         String s1_subcode = array1[2]; 
         String s1_sname = array1[3]; 
         String s1_groupid = array1[4]; 
         String s1_tag = array1[5]; 
         
           
         String s2_lecname1 = array2[0];  
         String s2_lecname2 = array2[1]; 
         String s2_subcode = array2[2]; 
         String s2_sname = array2[3]; 
         String s2_groupid = array2[4]; 
         String s2_tag = array2[5]; 
         
         
         String sql = "INSERT INTO nonoversessions (s1_lecname1,s1_lecname2,s1_subcode,s1_subname,s1_groupid,s1_tag,s2_lecname1,s2_lecname2,s2_subcode,s2_subname,s2_groupid,s2_tag)VALUES('"+s1_lecname1+"','"+s1_lecname2+"','"+s1_subcode+"','"+s1_sname+"','"+s1_groupid +"','"+s1_tag+"','"+s2_lecname1+"','"+s2_lecname2+"','"+s2_subcode+"','"+s2_sname+"','"+s2_groupid+"','"+s2_tag+"')";
         try
                 {
             
                     
                      pst = conn.prepareStatement(sql);
               
              pst.execute();
             JOptionPane.showMessageDialog(null, "Nonover lapping session  added");
             
       }
        catch(Exception e)
            
        {
            JOptionPane.showMessageDialog(null, "error  while adding data");
        }
    
         
   
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
           String val = Sserach.getText().toString();
                 
                 
                 int a; 
                 
                 try {
                     
                        pst  = conn.prepareStatement("select * from Session where id like '%"+val+"%'");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
         
            df1 = (DefaultTableModel)jTable2.getModel();
          
    
            df1.setRowCount(0);
           
            
            while(rs.next())
            {
            
            Vector v2 = new Vector();
             for(int i=1; i<=a; i++)
                 
                 
             {
             v2.add(rs.getString("id"));
                    v2.add(rs.getString("name1"));
                    v2.add(rs.getString("name2"));
                    v2.add(rs.getString("s_code"));
                    v2.add(rs.getString("s_name"));
                    v2.add(rs.getString("gid"));
                    v2.add(rs.getString("tag"));
                    v2.add(rs.getString("nuofstu"));
                    v2.add(rs.getString("duration"));
                    v2.add(rs.getString("alldetails"));
             
             }
         
            df1.addRow(v2);
         
            }
                     
                        
            
        } catch (Exception e) {
        }
                    
        
        
        

    }//GEN-LAST:event_jButton12ActionPerformed

    private void SserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SserachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SserachActionPerformed

    private void Sserach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sserach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sserach1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
           String val = Sserach1.getText().toString();
                 
                 
                 int a; 
                 
                 try {
                     
                        pst  = conn.prepareStatement("select * from Session where id like '%"+val+"%'");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
         
           df  =  (DefaultTableModel)jTable3.getModel();
            
           df.setRowCount(0);
          
           
            
            while(rs.next())
            {
            
            Vector v2 = new Vector();
             for(int i=1; i<=a; i++)
                 
                 
             {
             v2.add(rs.getString("id"));
                    v2.add(rs.getString("name1"));
                    v2.add(rs.getString("name2"));
                    v2.add(rs.getString("s_code"));
                    v2.add(rs.getString("s_name"));
                    v2.add(rs.getString("gid"));
                    v2.add(rs.getString("tag"));
                    v2.add(rs.getString("nuofstu"));
                    v2.add(rs.getString("duration"));
                    v2.add(rs.getString("alldetails"));
             
             }
           df.addRow(v2);
        
         ;
            }
                     
                        
            
        } catch (Exception e) {
        }
        
        
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void Ssearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ssearch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ssearch3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
          String val = Ssearch3.getText().toString();
                 
                 
                 int a; 
                 
                 try {
                     
                        pst  = conn.prepareStatement("select * from Session where id like '%"+val+"%'");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
         
           df2  =  (DefaultTableModel)jTable1.getModel();
            
           df2.setRowCount(0);
          
           
            
            while(rs.next())
            {
            
            Vector v2 = new Vector();
             for(int i=1; i<=a; i++)
                 
                 
             {
             v2.add(rs.getString("id"));
                    v2.add(rs.getString("name1"));
                    v2.add(rs.getString("name2"));
                    v2.add(rs.getString("s_code"));
                    v2.add(rs.getString("s_name"));
                    v2.add(rs.getString("gid"));
                    v2.add(rs.getString("tag"));
                    v2.add(rs.getString("nuofstu"));
                    v2.add(rs.getString("duration"));
                    v2.add(rs.getString("alldetails"));
             
             }
           df2.addRow(v2);
        
         ;
            }
                     
                        
            
        } catch (Exception e) {
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       AddNotAvailableTimes as = new AddNotAvailableTimes();
        as.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session_manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ssearch3;
    private javax.swing.JTextField Sserach;
    private javax.swing.JTextField Sserach1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private java.awt.Menu menu1;
    private java.awt.Menu menu10;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.Menu menu9;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private java.awt.MenuBar menuBar5;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
