/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author 94763
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public Student() {
        initComponents();
                                                                        
          
       
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Toppanel10 = new javax.swing.JPanel();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Student Group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 230, 100));

        Toppanel10.setBackground(new java.awt.Color(0, 153, 255));

        jButton95.setBackground(new java.awt.Color(247, 227, 147));
        jButton95.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton95.setText("Subjects");
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95jButton1ActionPerformed(evt);
            }
        });

        jButton96.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton96.setText("Home");
        jButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton96jButton2ActionPerformed(evt);
            }
        });

        jButton97.setBackground(new java.awt.Color(251, 149, 238));
        jButton97.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton97.setText("Work Time");
        jButton97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton97jButton3ActionPerformed(evt);
            }
        });

        jButton98.setBackground(new java.awt.Color(170, 221, 251));
        jButton98.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton98.setText("Leturers");
        jButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton98jButton4ActionPerformed(evt);
            }
        });

        jButton99.setBackground(new java.awt.Color(44, 253, 236));
        jButton99.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton99.setText("Tags");
        jButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton99jButton5ActionPerformed(evt);
            }
        });

        jButton100.setBackground(new java.awt.Color(246, 184, 113));
        jButton100.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton100.setText("Sessions");
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100jButton6ActionPerformed(evt);
            }
        });

        jButton101.setBackground(new java.awt.Color(169, 255, 155));
        jButton101.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton101.setText("Students");
        jButton101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton101jButton7ActionPerformed(evt);
            }
        });

        jButton102.setBackground(new java.awt.Color(255, 172, 172));
        jButton102.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton102.setText("Locations");
        jButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton102jButton8ActionPerformed(evt);
            }
        });

        jButton103.setBackground(new java.awt.Color(246, 253, 137));
        jButton103.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton103.setText("Generate");
        jButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton103jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Toppanel10Layout = new javax.swing.GroupLayout(Toppanel10);
        Toppanel10.setLayout(Toppanel10Layout);
        Toppanel10Layout.setHorizontalGroup(
            Toppanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Toppanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton96, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton97)
                .addGap(18, 18, 18)
                .addComponent(jButton98)
                .addGap(18, 18, 18)
                .addComponent(jButton95)
                .addGap(18, 18, 18)
                .addComponent(jButton99, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton100)
                .addGap(18, 18, 18)
                .addComponent(jButton101)
                .addGap(18, 18, 18)
                .addComponent(jButton102)
                .addGap(18, 18, 18)
                .addComponent(jButton103)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Toppanel10Layout.setVerticalGroup(
            Toppanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Toppanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Toppanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Toppanel10Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(Toppanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton100, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jButton96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(Toppanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Manage Student Groups");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 240, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         studentGroup as = new studentGroup();
             as.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton95jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95jButton1ActionPerformed
       Subjects in = new Subjects();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton95jButton1ActionPerformed

    private void jButton96jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96jButton2ActionPerformed
       Dashboard in = new Dashboard();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton96jButton2ActionPerformed

    private void jButton97jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton97jButton3ActionPerformed
        MainWorkTime in = new MainWorkTime();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton97jButton3ActionPerformed

    private void jButton98jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton98jButton4ActionPerformed
        Lecturers in = new Lecturers();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton98jButton4ActionPerformed

    private void jButton99jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton99jButton5ActionPerformed
        // TODO add your handling code here:
          
        tags as = new tags();
             as.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton99jButton5ActionPerformed

    private void jButton100jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100jButton6ActionPerformed
        Sessions in = new Sessions();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton100jButton6ActionPerformed

    private void jButton101jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton101jButton7ActionPerformed
         Student in = new Student();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton101jButton7ActionPerformed

    private void jButton102jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton102jButton8ActionPerformed
       LocationMain in = new LocationMain();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton102jButton8ActionPerformed

    private void jButton103jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton103jButton9ActionPerformed
       Generate in = new Generate();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton103jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       ManageSGroups as = new ManageSGroups();
             as.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Toppanel10;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
