/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Manujaya
 */
public class LocationManage extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst =null;
    ResultSet rs=null;
    DefaultTableModel model = new DefaultTableModel();
    
    public LocationManage() {
        initComponents();
        
        Object col[] = {"Location ID", "Building", "Room", "Related Subject", "Capacity", "Room Type"};
        model.setColumnIdentifiers(col);
        jTable2.setModel(model);
        
        conn = LocationManage.ConnectDb();
        
        //updateTable();
        load();
        
        setResizable(false);
        //screen center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Building = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Room = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Capacity = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        RSubject = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Location Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, -1, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 51, 298, 33));

        Search.setBackground(new java.awt.Color(0, 102, 204));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 51, 88, 33));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LID", "Building", "Room", "Related Subject", "Capacity", "Room Type"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 698, 210));

        Update.setBackground(new java.awt.Color(0, 102, 204));
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 567, 88, 33));

        Delete.setBackground(new java.awt.Color(0, 102, 204));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 323, 88, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Building Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 392, -1, -1));

        Building.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingActionPerformed(evt);
            }
        });
        jPanel1.add(Building, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 388, 220, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Room Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 392, -1, -1));

        Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomActionPerformed(evt);
            }
        });
        jPanel1.add(Room, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 388, 220, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Capacity :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 462, -1, -1));

        Capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacityActionPerformed(evt);
            }
        });
        jPanel1.add(Capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 458, 220, 29));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Lecture Hall");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 524, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Room Type:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 528, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Laboratory");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 524, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Related Subject");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 462, -1, -1));

        RSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSubjectActionPerformed(evt);
            }
        });
        jPanel1.add(RSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 458, 220, 29));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void search( String query){
        
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        jTable2.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private String roomtype;
    
     public static Connection ConnectDb(){
        try
        {
        Class.forName("org.sqlite.JDBC");
        Connection conn = DriverManager.getConnection("jdbc:sqlite:ttms.db");
        return conn;
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
     
     
    
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       try{            
            int row = jTable2.getSelectedRow();
            String value = (jTable2.getModel().getValueAt(row, 0).toString());

            String sql = "UPDATE location SET building=?,room=?,r_subject=?,capacity=?,room_type=? where l_id="+value;
            pst = conn.prepareStatement(sql);

            pst.setString(1,Building.getText());
            pst.setString(2,Room.getText());
            pst.setString(3,RSubject.getText());
            pst.setString(4,Capacity.getText());
            if (jRadioButton1.isSelected()){
            roomtype="Lecture Hall";
            }
            if(jRadioButton1.isSelected()){
            roomtype="Laboratory";
            }
            pst.setString(5,roomtype);
//            pst.setString(6,txtRoom.getText());
//            pst.setString(7,txtStart.getText());
//            pst.setString(8,txtEnd.getText());

            pst.executeUpdate();

            
            JOptionPane.showMessageDialog(null,"Successfully Updated!");
            load();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something Went Wrong! "+e);
        
    }
       finally {
              try{
                rs.close();
                pst.close();
            }
        catch(Exception e) {
            
        }}
       
    }//GEN-LAST:event_UpdateActionPerformed

    private void BuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuildingActionPerformed

    private void RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomActionPerformed

    private void CapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacityActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
     
        String tblbuilding = tblModel.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String tblroom = tblModel.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String tblrsubject = tblModel.getValueAt(jTable2.getSelectedRow(), 3).toString();
        String tblcapacity = tblModel.getValueAt(jTable2.getSelectedRow(), 4).toString();
        
        Building.setText(tblbuilding);
        Room.setText(tblroom);
        RSubject.setText(tblrsubject);
        Capacity.setText(tblcapacity);
        
      
        
    }//GEN-LAST:event_jTable2MouseClicked

     
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try{
            int row=jTable2.getSelectedRow();
            String value=(jTable2.getModel().getValueAt(row, 0).toString());
            String sql ="DELETE FROM location WHERE l_id ="+value;
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            //Auto Refresh Table
            
            JOptionPane.showMessageDialog(null,"Successfully Deleted!");
            load();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Something Went Wrong "+e);
            }
        finally {
              try{
                rs.close();
                pst.close();
            }
        catch(Exception e) {
            
        }}
    }//GEN-LAST:event_DeleteActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        roomtype="Lecture Hall";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        roomtype="Laboratory";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void RSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSubjectActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
      
    }//GEN-LAST:event_txtsearchKeyPressed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String val = txtsearch.getText().toString();
        
        int a;
        
        try{
            pst = conn.prepareStatement("select * from location where building like '%"+val+"%'");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
            model = (DefaultTableModel)jTable2.getModel();
            model.setRowCount(0);
            
         while(rs.next()){
         
             Vector v2 = new Vector();
             for(int i = 1; i<=a; i++){
             
                 v2.add(rs.getString("l_id"));
                 v2.add(rs.getString("building"));
                 v2.add(rs.getString("room"));
                 v2.add(rs.getString("r_subject"));
                 v2.add(rs.getString("capacity"));
                 v2.add(rs.getString("room_type"));
             }
            
             model.addRow(v2);
         
         }
        }
        catch(Exception e){
        
            Logger.getLogger(LocationManage.class.getName()).log(Level.SEVERE, null, e);
        }
        finally {
              try{
                rs.close();
                pst.close();
            }
        catch(Exception e) {
            
        }}
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        
    }//GEN-LAST:event_txtsearchActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    
    public void load(){
    
        int a;
        try{
            pst = conn.prepareStatement("select * from location");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
            model = (DefaultTableModel)jTable2.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
            
                Vector v2 = new Vector();
                for(int i = 1; i<=a; i++){
                
                 v2.add(rs.getString("l_id"));
                 v2.add(rs.getString("building"));
                 v2.add(rs.getString("room"));
                 v2.add(rs.getString("r_subject"));
                 v2.add(rs.getString("capacity"));
                 v2.add(rs.getString("room_type"));
                
                }
                   model.addRow(v2);
            }
        }
        
        catch(Exception e){}
        finally {
              try{
                rs.close();
                pst.close();
            }
        catch(Exception e) {
            
        }}
    
    }
    
//    public void updateTable(){
//    
//        model = (DefaultTableModel) jTable2.getModel();
//        
//            int selected = jTable2.getSelectedRow();
//            int l_id = Integer.parseInt(model.getValueAt(selected, 0).toString());
//        
//            //String Lecture1 = txtname1.getSelectedItem().toString();
//            String building = Building.getText();        
//            String room = Room.getText();
//            String r_subject = RSubject.getText();        
//            String capacity = Room.getText();
//            //String room_type = 
//            
//            
//            String Details = building+"/"+room+"/"+r_subject+"/"+capacity+"/"+room_type;
//            String Details1 = building+"/"+room+"/"+r_subject+"/"+capacity+"/"+room_type;
//            
//            
//            int x = JOptionPane.showConfirmDialog(null, "Do you want to update Location Details?", "Update", JOptionPane.YES_NO_OPTION);
//            
//        if(x == 0)
//        {
//            try {
//                pst = conn.prepareStatement("update location set building =?, room =?, r_subject =?, capacity =?, room_type =? where l_id =?");
//                pst.setString(1,building);
//                pst.setString(2,room);
//                pst.setString(3,r_subject);
//                pst.setString(4,capacity);
//                pst.setString(5,room_type);
//                pst.setInt(6,l_id);
//                
//                pst.executeUpdate();
//                 
//                JOptionPane.showMessageDialog(this, "Session Updated Successfully");
//                
//                 
//                
//                //errorname.setText("");
//                //erroreid.setText("");
//                
//                load();
//            } catch (SQLException ex) {
//                Logger.getLogger(LocationManage.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//           
//        }
//        
//    }
    
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocationManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocationManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocationManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocationManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocationManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Building;
    private javax.swing.JTextField Capacity;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField RSubject;
    private javax.swing.JTextField Room;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
