/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablems;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 94763
 */
public final class ManageTag extends javax.swing.JFrame {
    
    
    
     
    //  Connection conn = null;
    //  PreparedStatement pst  = null;
    ResultSet rs= null;

    /**
     * Creates new form NewJFrame
     */
    public ManageTag() {
        initComponents();
         conn =  ManageTag.ConnectDb();
        load();
        setResizable(false);
        //srean center code
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    
      Connection conn;
    PreparedStatement pst;
    DefaultTableModel df ;
    
    
    
    
    
    
    
    
    
      public static Connection ConnectDb()
    {
        
        try
            
        {
            Class.forName("org.sqlite.JDBC");
                     Connection conn = DriverManager.getConnection("jdbc:sqlite:ttms.db");
                     return conn;
        }
        catch(Exception e)
                {
                    
                    JOptionPane.showMessageDialog(null, e);
                    return null;
                }
                
    }
      
      
               
    public void load ()
            
    {
        
                   String sql = "Select* from tag";
        
        int a;
        try {
            pst  = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a= rd.getColumnCount();
            df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            
            
            while(rs.next())
            {
            
            Vector v2 = new Vector();
             for(int i=1; i<=a; i++)
                 
                 
             {
                      v2.add(rs.getInt("t_id")); 
                 v2.add(rs.getString("subject"));
                   v2.add(rs.getString("subject_code"));
                     v2.add(rs.getString("relatedtag"));
                 
                                    
             
             }
            df.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageTag.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TagN = new javax.swing.JTextField();
        TagC = new javax.swing.JTextField();
        TBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tag Name", "Tag Code", "R "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 68, 574, 297));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 99, 117, 45));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 182, 117, 45));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tag Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 376, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tag Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 428, -1, -1));

        TagN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TagNActionPerformed(evt);
            }
        });
        jPanel1.add(TagN, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 376, 198, 29));
        jPanel1.add(TagC, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 427, 198, 30));

        TBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Tutorial", "Lab" }));
        jPanel1.add(TBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 475, 198, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Related Tags");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 475, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 267, 117, 45));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 29)); // NOI18N
        jLabel4.setText("Manage Tags");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 11, 211, 46));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablems/1799658.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TagNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TagNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TagNActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
         
        df = (DefaultTableModel)jTable1.getModel();

        int selected = jTable1.getSelectedRow();

      int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
       TagN.setText(df.getValueAt(selected, 1).toString());
        TagC.setText(df.getValueAt(selected, 2).toString());
    TBox.setSelectedItem(df.getValueAt(selected, 3).toString());
       
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
         
           df = (DefaultTableModel)jTable1.getModel();
                               
                               int selected = jTable1.getSelectedRow();
                         
                              int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
                               
                               
                  String tagname = TagN.getText();
                      String tagcode =TagC.getText();
                 String Rtag =  TBox.getSelectedItem().toString();
              
                   
                     
            
        try {
            pst =  conn.prepareStatement("update tag set subject = ?,subject_code  = ?, relatedtag = ? where t_id = ?");
            
            
            
                 
                  
                  
                   
                       
                         pst.setString(1,tagname);
                             pst.setString(2,tagcode);
                         pst.setString(3,Rtag );
                   pst.setInt(4,id);
                             
                            pst.executeUpdate();
                              JOptionPane.showMessageDialog(this,"Tags updated");
                           
                           TagN.setText("");
                              TagC.setText("");
                              TBox.setSelectedItem("");
                              
                              
                         
                                            load(); 
            //jButton1.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger( ManageTag.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
            
           df = (DefaultTableModel)jTable1.getModel();
                               
                               int selected = jTable1.getSelectedRow();
                         
                              int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
                                
                              int X =   JOptionPane.showConfirmDialog(null,"do you want delete","Delete",JOptionPane.YES_NO_OPTION);
        
        
            
                              if (X==0)
                              {
                                  try {
                                      
                                      
                                          pst =  conn.prepareStatement("Delete from tag where  t_id = ?");
                                         pst.setInt(1,id);
                                         pst.executeUpdate();
                                         
                                            JOptionPane.showMessageDialog(this,"tag deleted");
                                            
                                              
                           TagN.setText("");
                              TagC.setText("");
                              TBox.setSelectedItem("");
                              
                                         
                                             
                                            load(); 
                                         
                                  }
                                  
                                        
         catch (SQLException ex) {
            Logger.getLogger( ManageTag.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
                                  
                              }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                           TagN.setText("");
                              TagC.setText("");
                              TBox.setSelectedItem("");
                              
                                         
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TBox;
    private javax.swing.JTextField TagC;
    private javax.swing.JTextField TagN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
